# config.yaml
qBittorrent:
  host: "http://127.0.0.1:8080"
  username: ""
  password: ""

TMDb:
  api_key: ""

Jackett:
  api_key: ""
  server_url: "http://localhost:9117"
  categories:
    Music: "3000"
    Movies: "2000"
    TV: "5000"


MicrosoftGraph:
  client_id: ""
  tenant_id: ""
  scopes: ["Chat.ReadWrite"]
  cache_file_path: "token_cache.bin"

Jellyfin:
  server_url: ""
  api_key: ""

Spotify:
  client_id: ""
  client_secret: ""
